// <auto-generated />
using System;
using MedicineStock_Microservice.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedicineStock_Microservice.Migrations
{
    [DbContext(typeof(MedicineStockContext))]
    partial class MedicineStockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedicineStock_Microservice.Entity.MedicineStock", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChemicalComposition")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR(250)");

                    b.Property<DateTime>("DateOfExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfTabletsInStock")
                        .HasColumnType("int");

                    b.Property<string>("TargetAilment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("MedicineStock");

                    b.HasData(
                        new
                        {
                            Name = "Orthoherb",
                            ChemicalComposition = "Castor Plant,Adulsa,Neem",
                            DateOfExpiry = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfTabletsInStock = 10000,
                            TargetAilment = "Orthopaedics"
                        },
                        new
                        {
                            Name = "Cholecalciferol",
                            ChemicalComposition = "aspartame ,food dyes",
                            DateOfExpiry = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfTabletsInStock = 5000,
                            TargetAilment = "Orthopaedics"
                        },
                        new
                        {
                            Name = "Gaviscon",
                            ChemicalComposition = "sodium alginate, sodium bicarbonate",
                            DateOfExpiry = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfTabletsInStock = 2500,
                            TargetAilment = "General"
                        },
                        new
                        {
                            Name = "Dolo-650",
                            ChemicalComposition = "Acetaminophen , Dexbrompheniramine",
                            DateOfExpiry = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfTabletsInStock = 8000,
                            TargetAilment = "General"
                        },
                        new
                        {
                            Name = "Cyclopam",
                            ChemicalComposition = "Dicyclomine  , Paracetamol ",
                            DateOfExpiry = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfTabletsInStock = 12000,
                            TargetAilment = "Gynaecology"
                        },
                        new
                        {
                            Name = "Hilact",
                            ChemicalComposition = "Asparagus racemosus  , Anethum sowa ",
                            DateOfExpiry = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfTabletsInStock = 6000,
                            TargetAilment = "Gynaecology"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
